import { Poppins } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/contexts/ModalContext";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "eSIM Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <main>
          <ReduxProvider>
            <ModalProvider>
              {children}
              <Toaster position="top-right" />
            </ModalProvider>
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
