import { Poppins } from "next/font/google";
import Footer from "@/components/shared/footer/Footer";
import NavbarWrapper from "@/components/shared/navbar/NavbarWrapper";
import FeedbackModal from "@/components/shared/FeedbackModal";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "eSIM Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <NavbarWrapper />
      <div className={` ${poppins.className} min-h-[calc(100vh-140px)]`}>
        {children}
      </div>
      <FeedbackModal />
      <Footer />
    </>
  );
}
